#!/bin/bash

GIT_DIR=$(git rev-parse --show-toplevel)
"$GIT_DIR"/gradlew lintKotlin

status=$?

if [ $status -ne 0 ]; then
  echo "##############################"
  echo "#Lint failed, commit aborted.#"
  echo "##############################"
  exit 1
fi

exit 0
