spring:
  application:
    name: code-squirrel-app-api
  web.resources.add-mappings: false

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100
  servlet:
    encoding:
      charset: UTF-8
      force: true
---
spring:
  config:
    activate:
      on-profile: local
    import:
      - swagger.yml
---
spring:
  config:
    activate:
      on-profile: prod
---
